schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "spicy_svg"
version = "1.0.0"
name = "spicy_svg"
tagline = "This is another extension"
maintainer = "Jan-Hendrik Müller"
# Supported types: "add-on",
# "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = [
	"Animation",
	"Sequencer",
]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
platforms = [
	"windows-x64",
	"linux-x64",
	"macos-arm64",
	"macos-x64",
]

wheels = [
	"./wheels/lxml-5.3.2-cp311-cp311-macosx_10_9_universal2.whl",
	"./wheels/lxml-5.3.2-cp311-cp311-macosx_10_9_x86_64.whl",
	"./wheels/lxml-5.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
	"./wheels/lxml-5.3.2-cp311-cp311-win_amd64.whl",
	"./wheels/svg.path-6.3-py2.py3-none-any.whl",
]

